language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -r dev-requirements.txt
  - pip install -e .
  - pip install coveralls
script:
  # Normal unit tests.
  - coverage run --source=apyori setup.py test
  # Code quality check.
  - pyflakes apyori.py test/*.py
  # Integration test
  - apyori-run data/integration_test_input_1.tsv > result.txt
  - diff result.txt data/integration_test_output_1.txt
after_success:
  - coveralls
notifications:
  - email: false
